#ifndef KERNEL_CONFIG_H
#define KERNEL_CONFIG_H

#define KERNEL_LOAD_ADDR 0x40000000UL
#define KERNEL_IDMAP_SIZE 0x01000000UL
#define EL0_SANDBOX_SIZE 0x00200000UL
#define EL0_SANDBOX_BASE (KERNEL_LOAD_ADDR + KERNEL_IDMAP_SIZE - EL0_SANDBOX_SIZE)
#define EL0_SANDBOX_END (EL0_SANDBOX_BASE + EL0_SANDBOX_SIZE)
#define EL0_CODE_SIZE 0x00010000UL
#define EL0_CODE_END (EL0_SANDBOX_BASE + EL0_CODE_SIZE)
#define EL0_TASK_C_STACK_BOTTOM 0x40FA0000UL
#define EL0_TASK_C_STACK_TOP 0x40FC0000UL
#define EL0_TASK_A_STACK_BOTTOM 0x40FC0000UL
#define EL0_TASK_A_STACK_TOP 0x40FE0000UL
#define EL0_TASK_B_STACK_BOTTOM 0x40FE0000UL
#define EL0_TASK_B_STACK_TOP 0x41000000UL

#ifndef DEBUG_TICK
#define DEBUG_TICK 1
#endif

#ifndef DEBUG_EARLY
#define DEBUG_EARLY 0
#endif

#define BENCH_ITERATIONS 1000U

#if defined(KERNEL_FLAVOR_MONO)
#define KERNEL_FLAVOR_STR "MONO"
#elif defined(KERNEL_FLAVOR_MICRO)
#define KERNEL_FLAVOR_STR "MICRO"
#else
#define KERNEL_FLAVOR_STR "MONO"
#endif

#if defined(BENCH_MODE_OFF)
#define BENCH_MODE_STR "OFF"
#elif defined(BENCH_MODE_LATENCY)
#define BENCH_MODE_STR "LATENCY"
#elif defined(BENCH_MODE_RECOVERY)
#define BENCH_MODE_STR "RECOVERY"
#else
#define BENCH_MODE_STR "OFF"
#endif

/* Future (inactive): user VA layout used once per-process TTBR0 mappings exist.
#define USER_VA_BASE  0x40000000UL
#define USER_VA_SIZE  0x00200000UL
#define USER_STACK_TOP 0x40020000UL
*/

#endif
